''' Input file generated by generate_conduit_partitions.py. '''

import numpy as np

Numerics = {'AVParameter': 0.3,
 'ApplyLimiters': 'PositivityPreservingMultiphasevpT',
 'ArtificialViscosity': True,
 'ElementQuadrature': 'GaussLegendre',
 'FaceQuadrature': 'GaussLegendre',
 'L2InitialCondition': True,
 'SolutionBasis': 'LagrangeSeg',
 'SolutionOrder': 2,
 'Solver': 'DG'}

Mesh = {'ElementShape': 'Segment',
 'File': None,
 'NumElemsX': 400,
 'xmax': -150,
 'xmin': -1150.0}

Physics = {'ConvFluxNumerical': 'LaxFriedrichs',
 'Gas1': {'R': 287.0, 'gamma': 1.4},
 'Gas2': {'R': 461.3762486126526, 'c_p': 2288.0},
 'Liquid': {'E_m0': 0,
            'K': 10000000000.0,
            'c_m': 3000.0,
            'p0': 35999999.99999999,
            'rho0': 2600.0},
 'Solubility': {'k': 5e-06, 'n': 0.5},
 'Type': 'MultiphasevpT',
 'Viscosity': {'mu0': 300000.0},
 'tau_d': 1.0}

SourceTerms = {
#     'source1': {'Function': 'GravitySource',
#              'gravity': 9.8,
#              'source_treatment': 'Explicit'},
#  'source2': {'Function': 'FrictionVolFracVariableMu',
#              'conduit_radius': 50,
#              'source_treatment': 'Explicit'},
#  'source3': {'Function': 'ExsolutionSource',
#              'source_treatment': 'Explicit',
#              'tau_d': 10.0},
#  'source4': {'Function': 'FragmentationTimescaleSourceSmoothed',
#              'crit_volfrac': 0.7,
#              'source_treatment': 'Explicit',
#              'tau_f': 1.0,
#              'fragsmooth_scale': 0.002,
#              "fake_parameter": 23,}
             }


Output = {'AutoPostProcess': False,
 'Prefix': 'cosine_inlet_test_conduit',
 'WriteInitialSolution': True,
 'WriteInterval': 100}

InitialCondition = {'Function': 'SteadyState',
 'K_magma': 10000000000.0,
 'T_chamber': 1050,
 'approx_massfracs': True,
 'c_v_magma': 3000.0,
 'conduit_radius': 50,
 'crit_volfrac': 0.7,
 'inlet_input_val': 40000000.0,
 'input_type': 'p',
 'neglect_edfm': True,
 'p0_magma': 35999999.99999999,
 'p_vent': 100000.0,
 'rho0_magma': 2600.0,
 'solubility_k': 5e-06,
 'solubility_n': 0.5,
 'tau_d': 10.0,
 'tau_f': 1.0,
 'x_global': np.linspace(-1.150e+03, -150.0, 401),
 'yA': 1e-07,
 'yC': lambda t: 0.4,
 'yCMin': 1e-05,
 'yWt': lambda t: 0.03 * (1.0 - 0.4) / (1.0 + 0.03),
 'yWvInletMin': 1e-05}

ExactSolution = {'Function': 'RiemannProblem'}

BoundaryConditions = {'x1': {'BCType': 'PressureStableLinearizedInlet1D',
        'T_chamber': 1050,
        'is_gaussian': False,
        'cVFamp': 0.1,
        'cVFav': 0.4,
        'chi_water': 0.03,
        'p_chamber': 40e6,
        'cos_freq': 3.0,
        'gaussian_sig': 4,
        'gaussian_tpulse': 20,
        'trace_arho': 2.6000000000000002e-05,},
 'x2': {'BCType': 'SlipWall'}}

LinkedSolvers = []# [{'BoundaryName': 'comm1D_0_1', 'DeckName': 'gaussianPulse_conduit_sub1.py'}]

TimeStepping = {'FinalTime': 1,
 'InitialTime': 0.0,
 'NumTimeSteps': 10000,
 'TimeStepper': 'RK3SR'}

# Restart = {'File': 'inlet_test_conduit_100.pkl',
#  'StartFromFileTime': False}