''' Input file generated by generate_conduit_partitions.py. '''

import numpy as np

Numerics = {'AVParameter': 0.3,
 'ApplyLimiters': 'PositivityPreservingMultiphasevpT',
 'ArtificialViscosity': True,
 'ElementQuadrature': 'GaussLegendre',
 'FaceQuadrature': 'GaussLegendre',
 'L2InitialCondition': False,
 'SolutionBasis': 'LagrangeSeg',
 'SolutionOrder': 2,
 'Solver': 'DG'}

Mesh = {'ElementShape': 'Segment',
 'File': None,
 'NumElemsX': 400,
 'xmax': -4950.0,
 'xmin': -6150.0}

Physics = {'ConvFluxNumerical': 'LaxFriedrichs', 'Type': 'MultiphasevpT'}

SourceTerms = {'source1': {'Function': 'GravitySource',
             'gravity': 9.8,
             'source_treatment': 'Explicit'},
 'source2': {'Function': 'FrictionVolFracVariableMu',
             'conduit_radius': 50,
             'source_treatment': 'Explicit'},
 'source3': {'Function': 'ExsolutionSource',
             'source_treatment': 'Explicit',
             'tau_d': 1.0},
 'source4': {'Function': 'FragmentationTimescaleSource',
             'crit_volfrac': 0.8,
             'source_treatment': 'Explicit',
             'tau_f': 1.0}}

Output = {'AutoPostProcess': False,
 'Prefix': '/scratch/users/kcoppess/ODEsteadyState/conduit_sub0',
 'WriteInitialSolution': True,
 'WriteInterval': 800}

InitialCondition = {'Function': 'SteadyState',
 'K_magma': 10000000000.0,
 'T_chamber': 1000,
 'c_v_magma': 3000.0,
 'conduit_radius': 50,
 'crit_volfrac': 0.8,
 'inlet_input_val': 1.0,
 'input_type': 'u',
 'p0_magma': 5000000.0,
 'p_vent': 100000.0,
 'rho0_magma': 2700.0,
 'solubility_k': 5e-06,
 'solubility_n': 0.5,
 'tau_d': 1.0,
 'tau_f': 1.0,
 'x_global': np.unique(np.hstack([np.linspace(-6.150e+03, -4.950e+03, 801), np.linspace(-4.950e+03, -3.750e+03, 801), np.linspace(-3.750e+03, -2.550e+03, 801), np.linspace(-2.550e+03, -1.350e+03, 801), np.linspace(-1.350e+03, -1.500e+02, 801)])),
 'yA': 1e-07,
 'yC': 0.4025,
 'yCMin': 1e-07,
 'yWt': 0.028750297463233536,
 'yWvInletMin': 1e-07}

ExactSolution = {'Function': 'RiemannProblem'}

BoundaryConditions = {'x1': {'BCType': 'VelocityInlet1D',
        'T_chamber': 1000,
        'p_chamber': 100000000.0,
        'trace_arho': 0.00027,
        'u': 1.0},
 'x2': {'BCType': 'MultiphasevpT1D1D', 'bkey': 'comm1D_0_1'}}

LinkedSolvers = [{'BoundaryName': 'comm1D_0_1', 'DeckName': 'conduit_sub1.py'}]

TimeStepping = {'FinalTime': 5,
 'InitialTime': 0.0,
 'NumTimeSteps': 20000,
 'TimeStepper': 'SSPRK3'}

