''' Input file generated by generate_conduit_partitions.py. '''

import numpy as np

Numerics = {'AVParameter': 500,
 'ApplyLimiters': 'PositivityPreservingMultiphasevpT',
 'ArtificialViscosity': True,
 'ElementQuadrature': 'GaussLegendre',
 'FaceQuadrature': 'GaussLegendre',
 'L2InitialCondition': False,
 'SolutionBasis': 'LagrangeSeg',
 'SolutionOrder': 1,
 'Solver': 'DG'}

Mesh = {'ElementShape': 'Segment',
 'File': None,
 'NumElemsX': 400,
 'xmax': -750.0,
 'xmin': -950.0}

Physics = {'ConvFluxNumerical': 'LaxFriedrichs', 'Type': 'MultiphasevpT'}

SourceTerms = {'source1': {'Function': 'GravitySource',
             'gravity': 9.8,
             'source_treatment': 'Explicit'},
 'source2': {'Function': 'FrictionVolFracVariableMu',
             'source_treatment': 'Explicit'},
 'source3': {'Function': 'ExsolutionSource',
             'source_treatment': 'Implicit',
             'tau_d': 1.0},
 'source4': {'Function': 'FragmentationTimescaleSource',
             'source_treatment': 'Explicit',
             'tau_f': 1.0}}

Output = {'AutoPostProcess': False,
 'Prefix': '/scratch/users/kcoppess/steadyState/test_conduit_sub6',
 'WriteInitialSolution': True,
 'WriteInterval': 800}

InitialCondition = {'Function': 'RiemannProblem',
 'x_global': np.unique(np.hstack([np.linspace(-2.150e+03, -1.950e+03, 401), np.linspace(-1.950e+03, -1.750e+03, 401), np.linspace(-1.750e+03, -1.550e+03, 401), np.linspace(-1.550e+03, -1.350e+03, 401), np.linspace(-1.350e+03, -1.150e+03, 401), np.linspace(-1.150e+03, -9.500e+02, 401), np.linspace(-9.500e+02, -7.500e+02, 401), np.linspace(-7.500e+02, -5.500e+02, 401), np.linspace(-5.500e+02, -3.500e+02, 401), np.linspace(-3.500e+02, -1.500e+02, 401)]))}

ExactSolution = {'Function': 'RiemannProblem'}

BoundaryConditions = {'x1': {'BCType': 'MultiphasevpT1D1D', 'bkey': 'comm1D_5_6'},
 'x2': {'BCType': 'MultiphasevpT1D1D', 'bkey': 'comm1D_6_7'}}

LinkedSolvers = [{'BoundaryName': 'comm1D_6_7', 'DeckName': 'conduit_sub7.py'}]

