''' Input file generated by generate_conduit_partitions.py. '''

import numpy as np

Numerics = {'AVParameter': 0.3,
 'ApplyLimiters': 'PositivityPreservingMultiphasevpT',
 'ArtificialViscosity': True,
 'ElementQuadrature': 'GaussLegendre',
 'FaceQuadrature': 'GaussLegendre',
 'L2InitialCondition': True,
 'SolutionBasis': 'LagrangeSeg',
 'SolutionOrder': 2,
 'Solver': 'DG'}

Mesh = {'ElementShape': 'Segment',
 'File': None,
 'NumElemsX': 200,
 'xmax': -850.0,
 'xmin': -950.0}

Physics = {'ConvFluxNumerical': 'LaxFriedrichs',
 'Gas1': {'R': 287.0, 'gamma': 1.4},
 'Gas2': {'R': 461.3762486126526, 'c_p': 2288.0},
 'Liquid': {'E_m0': 0,
            'K': 10000000000.0,
            'c_m': 3000.0,
            'p0': 35999999.99999999,
            'rho0': 2600.0},
 'Solubility': {'k': 5e-06, 'n': 0.5},
 'Type': 'MultiphasevpT',
 'Viscosity': {'mu0': 300000.0},
 'tau_d': 1.0}

SourceTerms = {'source1': {'Function': 'GravitySource',
             'gravity': 9.8,
             'source_treatment': 'Explicit'},
 'source2': {'Function': 'FrictionVolFracVariableMu',
             'conduit_radius': 50,
             'source_treatment': 'Explicit'},
 'source3': {'Function': 'ExsolutionSource',
             'source_treatment': 'Explicit',
             'tau_d': 10.0},
 'source4': {'Function': 'FragmentationTimescaleSourceSmoothed',
             'crit_volfrac': 0.7,
             'fragsmooth_scale': 0.05,
             'source_treatment': 'Explicit',
             'tau_f': 1.0}}

Output = {'AutoPostProcess': False,
 'Prefix': '/scratch/users/kcoppess/pressureBC/gp_sig4/conduit_sub2',
 'WriteInitialSolution': True,
 'WriteInterval': 540}

InitialCondition = {'Function': 'SteadyState',
 'K_magma': 10000000000.0,
 'T_chamber': 1050,
 'approx_massfracs': True,
 'c_v_magma': 3000.0,
 'conduit_radius': 50,
 'crit_volfrac': 0.7,
 'fragsmooth_scale': 0.05,
 'inlet_input_val': 40000000.0,
 'input_type': 'p',
 'neglect_edfm': True,
 'p0_magma': 35999999.99999999,
 'p_vent': 100000.0,
 'rho0_magma': 2600.0,
 'solubility_k': 5e-06,
 'solubility_n': 0.5,
 'tau_d': 10.0,
 'tau_f': 1.0,
 'x_global': np.unique(np.hstack([np.linspace(-1.150e+03, -1.050e+03, 401), np.linspace(-1.050e+03, -9.500e+02, 401), np.linspace(-9.500e+02, -8.500e+02, 401), np.linspace(-8.500e+02, -7.500e+02, 401), np.linspace(-7.500e+02, -6.500e+02, 401), np.linspace(-6.500e+02, -5.500e+02, 401), np.linspace(-5.500e+02, -4.500e+02, 401), np.linspace(-4.500e+02, -3.500e+02, 401), np.linspace(-3.500e+02, -2.500e+02, 401), np.linspace(-2.500e+02, -1.500e+02, 401)])),
 'yA': 1e-07,
 'yC': lambda t: 0.4,
 'yCMin': 1e-05,
 'yWt': lambda t: 0.03 * (1.0 - 0.4) / (1.0 + 0.03),
 'yWvInletMin': 1e-05}

ExactSolution = {'Function': 'RiemannProblem'}

BoundaryConditions = {'x1': {'BCType': 'MultiphasevpT1D1D', 'bkey': 'comm1D_1_2'},
 'x2': {'BCType': 'MultiphasevpT1D1D', 'bkey': 'comm1D_2_3'}}

LinkedSolvers = [{'BoundaryName': 'comm1D_2_3', 'DeckName': 'gp_sig4_conduit_sub3.py'}]

